### ISSUE TITLE
Uses Twitter API v2

### ISSUE THREAD

**Issue by Eomm** [ethomson/twitter-action#19]
Using this action for the first time leads to:

```
  {
    message: 'You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve',
    code: 453
  }
```

Right now, requesting Elevated access is not necessary actually thanks to the Twitter API v2.

As shown here: https://developer.twitter.com/en/docs/twitter-api/migrate/twitter-api-endpoint-map
it is necessary to move from the `statuses/update` API to [the v2 interface](https://www.postman.com/twitter/workspace/twitter-s-public-workspace/request/9956214-5bd6ebb1-9d79-4456-a9a6-22ead4a41625?ctx=code):

```
curl --location --request POST 'https://api.twitter.com/2/tweets' \
--data-raw '{
    "text": "Hello World!"
}'
```

**Comment by DominiqueMakowski** [comment]
I have the same error

**Comment by Eomm** [comment]
I have created a new action for this reason

https://github.com/Eomm/why-don-t-you-tweet

**Comment by eumel8** [comment]
@Eomm works, thx!

**Comment by vsoch** [comment]
hey @ethomson I wanted to check in to follow up on the issue here - is support of the v2 API implemented? Thank you!

**Comment by Eomm** [comment]
Closing as I built a replacement https://github.com/Eomm/why-don-t-you-tweet
